services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt  # Install dependencies
    startCommand: |
      python manage.py migrate --noinput  # Apply migrations
      python manage.py runserver 0.0.0.0:8000  # Start the server
