services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt  # Install dependencies
    startCommand: sh entrypoint.sh python manage.py runserver 0.0.0.0:8000  # Run migrations and start server
