# Generated by Django 5.1.4 on 2025-02-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='temp_field',
        ),
    ]
