# Generated by Django 5.1.4 on 2025-02-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_member_temp_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='temp_field',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
