# Generated by Django 5.0.4 on 2025-07-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_assignmentsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentsubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
