# Generated by Django 5.0.4 on 2025-07-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_assignmentsubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentsubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Assignment Submission', 'verbose_name_plural': 'Assignment Submissions'},
        ),
    ]
