# Generated by Django 5.1.4 on 2025-02-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_withdrawal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
