# Generated by Django 5.1.4 on 2025-02-17 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_withdrawal_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
