# Generated by Django 5.1.4 on 2025-02-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_withdrawal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_collected_stage1',
            field=models.BooleanField(default=False),
        ),
    ]
