# Generated by Django 5.1.4 on 2025-02-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_profile_has_collected_stage1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_collected_stage1',
        ),
    ]
