# Generated by Django 5.1.4 on 2025-02-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_profile_has_collected_stage1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
