# Generated by Django 5.1.4 on 2025-03-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_withdrawal_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=50)),
                ('interest', models.TextField()),
                ('internship', models.CharField(max_length=3)),
                ('updates', models.CharField(max_length=3)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
