# Generated by Django 5.1.4 on 2025-03-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_sponsorshipsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshipsurvey',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sponsorshipsurvey',
            name='internship',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
