# Generated by Django 5.1.4 on 2025-05-28 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_sponsorshipsurvey_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
