# Generated by Django 5.1.4 on 2025-06-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_withdrawal_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='earnings',
            field=models.IntegerField(default=0),
        ),
    ]
