# Generated by Django 5.1.4 on 2025-06-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_member_earnings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='earnings',
        ),
        migrations.AddField(
            model_name='profile',
            name='earnings',
            field=models.IntegerField(default=0),
        ),
    ]
